// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhanajsppwcyradkgupj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoYW5hanNwcHdjeXJhZGtndXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTMxOTAsImV4cCI6MjA2NTQ2OTE5MH0.gLoK2QyE4HuKhWERh2TUrwLxvC218s-Fn1p0nqexwzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);